version: '3.8'

services:
  frontend:
    build: ./smart-seat
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://backend:5000

  backend:
    build: ./smart-seat-backend
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=asdfgh123
      - DB_NAME=smart_seat
      - PORT=5000
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=asdfgh123
      - MYSQL_DATABASE=smart_seat
    volumes:
      - mysql-data:/var/lib/mysql
      - ./smart-seat-backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: